function wallsMat = createMaze()

    gameBoard = pacBoard();
    wallsMat = makeMaze(gameBoard);

end


% ========================================================================
function wallsMat = makeMaze(curBoard)

    wallsMat = [];
    t = 1;

    for ii = 1:length(curBoard(:,1))
        for jj = 1:length(curBoard(1,:))

            if curBoard(ii,jj) && ~curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+6,1:2) = [ii-t jj;...
                    ii-t jj-t;...
                    ii jj-t;...
                    ii jj;...
                    ii-t jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+5,1:2) = [ii-t jj;...
                    ii-t jj-t;...
                    ii jj-t;...
                    ii jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+5,1:2) = [ii jj-t;...
                    ii jj;...
                    ii-t jj;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+6,1:2) = [ii jj-t;...
                    ii jj;...
                    NaN NaN;...
                    ii-t jj;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+5,1:2) = [ii-t jj;...
                    ii jj;...
                    ii jj-t;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+5,1:2) = [ii jj-t;...
                    ii-t jj-t;...
                    ii-t jj;...
                    ii jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+6,1:2) = [ii-t jj;...
                    ii jj;...
                    NaN NaN;...
                    ii jj-t;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+4,1:2) = [ii jj-t;...
                    ii-t jj-t;...
                    ii-t jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+4,1:2) = [ii jj-t;...
                    ii jj;...
                    ii-t jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && curBoard(ii,jj-1) && curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+4,1:2) = [ii jj;...
                    ii-t jj;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+4,1:2) = [ii jj;...
                    ii jj-t;...
                    ii-t jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && ~curBoard(ii,jj+1) && curBoard(ii,jj-1) && curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+3,1:2) = [ii-t jj;...
                    ii jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && ~curBoard(ii,jj-1) && curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+3,1:2) = [ii-t jj-t;...
                    ii jj-t;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && curBoard(ii,jj-1) && curBoard(ii+1,jj) && ~curBoard(ii-1,jj)
                wallsMat(end+1:end+3,1:2) = [ii-t jj-t;...
                    ii-t jj;...
                    NaN NaN];

            elseif curBoard(ii,jj) && curBoard(ii,jj+1) && curBoard(ii,jj-1) && ~curBoard(ii+1,jj) && curBoard(ii-1,jj)
                wallsMat(end+1:end+3,1:2) = [ii jj-t;...
                    ii jj;...
                    NaN NaN];
            end
        end
    end
end
% ========================================================================
